endwithls = (
     ".fi", ".com", ".net", ".org", ".info", ".biz", ".io", ".me", ".co", ".tv",
    ".us", ".uk", ".de", ".jp", ".cn", ".eu", ".ru", ".in", ".au", ".ca",
    ".fr", ".it", ".nl", ".es", ".se", ".no", ".dk", ".pl", ".ch", ".at",
    ".be", ".mx", ".br", ".ar", ".pt", ".tr", ".il", ".gr", ".kr", ".hk",
    ".sg", ".za", ".cl", ".nz", ".id", ".ph", ".th", ".my", ".vn", ".tw",
    ".cz", ".sk", ".ua", ".ro", ".bg", ".hu", ".lt", ".lv", ".ee", ".hr",
    ".si", ".rs", ".by", ".md", ".ge", ".am", ".kz", ".kg", ".uz", ".mn",
    ".ae", ".qa", ".bh", ".sa", ".om", ".eg", ".ma", ".tn", ".dz", ".ng",
    ".ke", ".gh", ".tz", ".ug", ".et", ".zm", ".mw", ".ls", ".zw", ".bw",
    ".na", ".mz", ".cd", ".ao", ".cm", ".sn", ".ci", ".bf", ".ml", ".gm",
    ".sl", ".lr", ".bi", ".rw", ".so", ".sd", ".ss", ".eh", ".ly", ".af",
    ".pk", ".np", ".bd", ".lk", ".bt", ".mv", ".kh", ".la", ".mm", ".bn",
    ".th", ".kg", ".tj", ".tm", ".ir", ".iq", ".sy", ".jo", ".ps", ".lb",
    ".cy", ".mt", ".al", ".xk", ".fo", ".is", ".gl", ".sh", ".pn", ".fk",
    ".gs", ".cc", ".cx", ".as", ".nu", ".tk", ".wf", ".tf", ".io", ".eh",
    ".bl", ".mf", ".gp", ".mq", ".re", ".yt", ".pm", ".tf", ".aq", ".bv",
    ".hm", ".sj", ".ax", ".int", ".mil", ".gov", ".edu", ".coop", ".museum",
    ".jobs", ".mobi", ".pro", ".aero", ".arpa", ".asia", ".cat", ".tel",
    ".travel", ".name", ".xxx", ".post", ".bank", ".insurance", ".attorney",
    ".doctor", ".pharmacy", ".law", ".luxe", ".app", ".dev", ".page", ".shop",
    ".store", ".art", ".design", ".health", ".tech", ".cloud", ".music", ".film",
    ".movie", ".actor", ".band", ".dj", ".fm", ".radio", ".stream", ".video",
    ".digital", ".photo", ".pictures", ".gallery", ".media", ".news", ".blog"
)